spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/task_db?currentSchema=task_dev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: task_dev

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yml

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: account-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      default-zone: http://localhost:8761/eureka/

server:
  port: 8110

logging:
  level:
    org.springframework.cloud.vault: DEBUG

security:
  jwt:
    secret: ${SECRET_KEY}

springdoc:
  swagger-ui:
    config-url: /task/v3/api-docs/swagger-config
    url: /task/v3/api-docs
  api-docs:
    path: /task/v3/api-docs