@path = http://localhost:8072/account
@accountId = b4010fe0-8b3b-4451-8f1d-487409596572

### GET all accounts
GET {{path}}

### GET by id
GET {{path}}/{{accountId}}

### POST create new account
POST {{path}}
Content-Type: application/json

{
  "name": "Timur",
  "surname": "Timur",
  "age": 25
}

### PUT update account
PUT {{path}}/{{accountId}}
Content-Type: application/json

{
  "accountId": "b4010fe0-8b3b-4451-8f1d-487409596572",
  "name": "Sanya",
  "surname": "Timur",
  "age": 22
}

### DELETE by id
DELETE {{path}}/{{accountId}}
