@path = http://localhost:8072/auth/api/v1/auth

### POST login
POST  {{path}}/login
Content-Type: application/json

{
  "username": "pasha12",
  "password": "root"
}

### POST register
POST  {{path}}/register
Content-Type: application/json

{
  "username": "Pasha4.14.24-USER2",
  "password": "root",
  "passwordConfirmation": "root"
}