@path = http://localhost:8072/profile
@profileId = b4010fe0-8b3b-4451-8f1d-487409596573


### GET page > totalPages
GET {{path}}?page=100000

### GET by invalid UUID
GET {{path}}/it's-invalid-UUID

### GET unexisted profile
GET {{path}}/{{profileId}}

### POST validation check
POST {{path}}
Content-Type: application/json

{
  "name": "",
  "surname": "D",
  "age": -25
}

### POST attempt creating with specified UUID
POST {{path}}
Content-Type: application/json

{
  "profileId": "f73185e5-99a6-45d5-bc62-15172237615f",
  "name": "Danil",
  "surname": "Danil",
  "age": 25
}

### PUT validation check
PUT {{path}}/{{profileId}}
Content-Type: application/json

{
  "name": "",
  "surname": "",
  "age": 122
}

### PUT path profileId mismatch with entity profileId
PUT {{path}}/{{profileId}}
Content-Type: application/json

{
  "profileId": "f73185e5-99a6-45d5-bc62-15172237615a",
  "name": "Sanya",
  "surname": "Sanya",
  "age": 22
}