@path = http://localhost:8072/profile/api/v1/profile

@profileId =f6184d8f-fa42-45f0-b0fe-a9d15fae348b

### GET all profiles
GET {{path}}
Authorization: Bearer {{accessToken}}

### GET by id
GET {{path}}/{{profileId}}
Authorization: Bearer {{accessToken}}

### POST create new profile
POST {{path}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Danil",
  "surname": "Semenov",
  "age": 25
}

### PUT update profile
PUT {{path}}/{{profileId}}
Content-Type: application/json

{
  "profileId": "b4010fe0-8b3b-4451-8f1d-487409596572",
  "name": "Sanya",
  "surname": "Timur",
  "age": 22
}

### DELETE by id
DELETE {{path}}/{{profileId}}
Authorization: Bearer {{accessToken}}