@path = http://localhost:8100/api/v1/profile
# много тасков
@accountId =68b1e612-733a-400e-8ef3-20f51c7d1cf7


### GET all accounts
GET {{path}}
Authorization: Bearer {{accessToken}}

### GET by id
GET {{path}}/{{accountId}}
Authorization: Bearer {{accessToken}}

### POST create new profile
POST {{path}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "name": "Danil",
  "surname": "Semenov",
  "age": 27
}

### PUT update profile
PUT {{path}}/{{accountId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "accountId": "{{accountId}}",
  "name": "Иван UPDATED BY ADMIN",
  "surname": "Semenov UPDATED BY ADMIN",
  "age": 24
}

### DELETE by id
DELETE {{path}}/{{accountId}}
Authorization: Bearer {{accessToken}}