server:
  port: 8072

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: account-service-api
              uri: lb://account-ms
              predicates:
                - Path=/account/**
              filters:
                - RewritePath=/account, /api/v1/account
            - id: account-service-swagger
              uri: lb://account-ms
              predicates:
                - Path=/account/swagger/**
              filters:
                - RewritePath=/account/swagger/(?<path>.*), /$\{path}

            - id: task-service-api
              uri: lb://task-ms
              predicates:
                - Path=/task/**
              filters:
                - RewritePath=/task, /api/v1/task
            - id: task-service-swagger
              uri: lb://task-ms  # URL первого микросервиса
              predicates:
                - Path=/task/swagger/**
              filters:
                - RewritePath=/task/swagger/(?<path>.*), /$\{path}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      default-zone: http://localhost:8761/eureka/

management:
  endpoint:
    gateway:
      access: read_only
  endpoints:
    web:
      exposure:
        include: gateway