server:
  port: 8072

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # Account paths
            - id: account-service-api
              uri: lb://account-ms
              predicates:
                - Path=/account/api/v1/**
              filters:
                - RewritePath=/account/api/v1/(?<path>.*), /api/v1/$\{path}

            - id: account-swagger-ui
              uri: lb://account-ms
              predicates:
                - Path=/account/swagger/**
              filters:
                - RewritePath=/account/swagger/(?<path>.*), /swagger-ui/$\{path}

            - id: account-api-docs
              uri: lb://account-ms
              predicates:
                - Path=/account/v3/**
              filters:
                - RewritePath=/account/v3/(?<path>.*), /account/v3/$\{path}

            # Task paths
            - id: task-service-api
              uri: lb://task-ms
              predicates:
                - Path=/task/api/v1/**
              filters:
                - RewritePath=/task/api/v1/(?<path>.*), /api/v1/$\{path}

            - id: task-swagger-ui
              uri: lb://task-ms
              predicates:
                - Path=/task/swagger/**
              filters:
                - RewritePath=/task/swagger/(?<path>.*), /swagger-ui/$\{path}

            - id: task-api-docs
              uri: lb://task-ms
              predicates:
                - Path=/task/v3/**
              filters:
                - RewritePath=/task/v3/(?<path>.*), /task/v3/$\{path}

            # Auth paths
            - id: auth-service-api
              uri: lb://auth-ms
              predicates:
                - Path=/auth/api/v1/**
              filters:
                - RewritePath=/auth/api/v1/(?<path>.*), /api/v1/$\{path}

            - id: auth-swagger-ui
              uri: lb://auth-ms
              predicates:
                - Path=/auth/swagger/**
              filters:
                - RewritePath=/auth/swagger/(?<path>.*), /swagger-ui/$\{path}

            - id: auth-api-docs
              uri: lb://auth-ms
              predicates:
                - Path=/auth/v3/**
              filters:
                - RewritePath=/auth/v3/(?<path>.*), /auth/v3/$\{path}

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      default-zone: http://localhost:8761/eureka/

management:
  endpoint:
    health:
      enabled: true
    gateway:
      access: read_only
  endpoints:
    web:
      exposure:
        include: gateway, health