server:
  port: 8072

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: account-service-api
              uri: lb://account-ms
              predicates:
                - Path=/account/api/v1/**
              filters:
                - RewritePath=/account/api/v1/(?<path>.*), /api/v1/$\{path}
            - id: account-service-swagger
              uri: lb://account-ms
              predicates:
                - Path=/account/swagger-ui.html
              filters:
                - SetPath=/swagger-ui.html

            - id: task-service-api
              uri: lb://task-ms
              predicates:
                - Path=/task/api/v1/**
              filters:
                - RewritePath=/task/api/v1/(?<path>.*), /api/v1/$\{path}
            - id: task-service-swagger
              uri: lb://task-ms
              predicates:
                - Path=/task/swagger
              filters:
                - SetPath=/swagger-ui.html

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      default-zone: http://localhost:8761/eureka/

management:
  endpoint:
    gateway:
      access: read_only
  endpoints:
    web:
      exposure:
        include: gateway