spring:
  cloud:
    vault:
      uri: http://vault:8200

  datasource:
    url: jdbc:postgresql://postgres:5432/auth_user_db?currentSchema=auth_user_dev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: auth_user_dev

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yml

  kafka:
    bootstrap-servers: kafka:9092
