spring:
  cloud:
    vault:
      uri: http://localhost:8200
      token: myroot
      kv:
        enabled: true
        backend: secret
        default-context: "kv/auth-ms"

  datasource:
    url: jdbc:postgresql://localhost:5432/auth_user_db?currentSchema=auth_user_dev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: auth_user_dev

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yml

  kafka:
    bootstrap-servers: localhost:9094
    consumer:
      group-id: authentication-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      default-zone: http://localhost:8761/eureka/

server:
  port: 8120

security:
  jwt:
    secret: ${SECRET_KEY}
    accessDuration: ${ACCESS_DURATION}
    refreshDuration: ${REFRESH_DURATION}

springdoc:
  swagger-ui:
    config-url: /auth/v3/api-docs/swagger-config
    url: /auth/v3/api-docs
  api-docs:
    path: /auth/v3/api-docs