services:
  # infrastructure services
  config-server:
    image: danilchet/zuzex-config-server-ms
    container_name: config-server-zuzex-container
    networks:
      - taskmanager_microservices-net
    ports:
      - "8071:8071"

  eureka-server:
    image: danilchet/zuzex-eureka-server-ms
    container_name: eureka-server-zuzex-container
    networks:
      - taskmanager_microservices-net
    ports:
      - "8761:8761"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8071
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8071
    depends_on:
      - config-server

  gateway-server:
    image: danilchet/zuzex-gateway-server-ms
    container_name: gateway-server-zuzex-container
    networks:
      - taskmanager_microservices-net
    ports:
      - "8072:8072"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8071
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8071
      #      - SPRING_PROFILES_ACTIVE=docker
      - "eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/"
    depends_on:
      - config-server

networks:
  taskmanager_microservices-net :
    external: true