services:
  # outer services
  postgres:
    image: postgres:16-alpine
    container_name: postgres-zuzex-container
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: license_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      PGDATA: /data/postgres
    networks:
      - microservices-net
    volumes:
      - postgres-volume:/data/postgres
    restart: unless-stopped

  vault:
    image: vault:1.13.3
    container_name: vault-zuzex-container
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-zuzex-container
    command: start-dev 
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
      KC_HOSTNAME: localhost
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak_db
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: root
    ports:
      - "8300:8080"
    networks:
      microservices-net:
        aliases:
          - "keycloak"

  # infrastructure services
  config-server:
    image: danilchet/zuzex-config-server-ms
    container_name: config-server-zuzex-container
    networks:
      - microservices-net
    ports:
      - "8071:8071"

  eureka-server:
    image: danilchet/zuzex-eureka-server-ms
    container_name: eureka-server-zuzex-container
    networks:
      - microservices-net
    ports:
      - "8761:8761"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8071
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8071
    depends_on:
      - config-server

  # main services


networks:
  microservices-net:
    driver: bridge
volumes:
  postgres-volume: