global:
  scrape_interval:     5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'authservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth-ms:8120']
  - job_name: 'taskservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['task-ms:8110']
  - job_name: 'profileservice'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['profile-ms:8100']
