services:
  # main services
  auth-ms:
    image: danilchet/zuzex-auth-ms
    container_name: auth-ms-zuzex-container
    networks:
      - task-manager
    ports:
      - "8120:8120"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8071
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8071
      - "eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/"

  account-ms:
    image: danilchet/zuzex-account-ms
    container_name: account-ms-zuzex-container
    networks:
      - task-manager
    ports:
      - "8100:8100"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8071
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8071
      - "eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/"

  task-ms:
    image: danilchet/zuzex-task-ms
    container_name: task-ms-zuzex-container
    networks:
      - task-manager
    ports:
      - "8110:8110"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8071
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8071
      - "eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/"

networks:
  task-manager:
    external: true