services:
  # infrastructure services
  config-server:
    image: danilchet/zuzex-config-server-ms
    container_name: config-server-zuzex-container
    networks:
      - task-manager
    ports:
      - "8071:8071"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8071/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  eureka-server:
    image: danilchet/zuzex-eureka-server-ms
    container_name: eureka-server-zuzex-container
    networks:
      - task-manager
    ports:
      - "8761:8761"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8071
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8071
    depends_on:
      config-server:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  gateway-server:
    image: danilchet/zuzex-gateway-server-ms
    container_name: gateway-server-zuzex-container
    networks:
      - task-manager
    ports:
      - "8072:8072"
    environment:
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8071
      - SPRING_CONFIG_IMPORT=configserver:http://config-server:8071
      #      - SPRING_PROFILES_ACTIVE=docker
      - "eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8072/actuator/health" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    depends_on:
      config-server:
        condition: service_healthy
      eureka-server:
        condition: service_healthy

networks:
  task-manager:
    external: true