@path = http://localhost:8100/api/v1/account
# много тасков
@accountId =e25be320-2e5d-4867-9a65-d8c49bbe17e2

@danilToken =eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJEYW5pbDUiLCJpZCI6ImUyNWJlMzIwLTJlNWQtNDg2Ny05YTY1LWQ4YzQ5YmJlMTdlMiIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJleHAiOjE3NTExMzA2Nzd9.buWCOwZD4_jm1vTWxf0MSszEt9HM4cZt_rDZmdOZ5rYUK-NOsJEPEEyj2JHXf5r02QFEC8Mtitlf46TGz8q9aQ
@adminToken =eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbjEiLCJpZCI6IjViYzM4OGE2LWY5NWQtNDU5ZC1iNWI1LTUxYjYzZTAxYzUzMyIsInJvbGVzIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwiZXhwIjoxNzUxMjE3NDY0fQ.sXPV4PonsqqSH5ALUFYXpSIEniHv4PNltBd_YaZz7EsdVGDXqpeKevrteCDVrNdjOrJB0iv-TOCbnvuXGqwGqg

### GET all accounts
GET {{path}}
Authorization: Bearer {{adminToken}}

### GET by id
GET {{path}}/{{accountId}}
Authorization: Bearer {{adminToken}}

### POST create new account
POST {{path}}
Content-Type: application/json
Authorization: Bearer {{danilToken}}

{
  "name": "!!! Test Pasha !!!",
  "surname": "!!! Test Pasha !!!",
  "age": 27
}

### PUT update account
PUT {{path}}/{{accountId}}
Content-Type: application/json
Authorization: Bearer {{danilToken}}

{
  "accountId": "{{accountId}}",
  "name": "Pashetet UPDATED BY ADMIN",
  "surname": "Petroshevich UPDATED BY ADMIN",
  "age": 24
}

### DELETE by id
DELETE {{path}}/{{accountId}}
Authorization: Bearer {{danilToken}}