@path = http://localhost:8100/api/v1/account
@accountId = 1664ca32-5d7d-43b9-adf8-455ba9de1318

### GET all accounts
GET {{path}}

### GET by id
GET {{path}}/{{accountId}}

### POST create new account
POST {{path}}
Content-Type: application/json

{
  "name": "Danil",
  "surname": "Danil",
  "age": 25
}

### PUT update account
PUT {{path}}/{{accountId}}
Content-Type: application/json

{
  "accountId": "f73185e5-99a6-45d5-bc62-15172237615f",
  "name": "Sanya",
  "surname": "Sanya",
  "age": 22
}

### DELETE by id
DELETE {{path}}/{{accountId}}
