@path = http://localhost:8100/api/v1/account
# много тасков
@accountId =e25be320-2e5d-4867-9a65-d8c49bbe17e2

@danilToken = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJEYW5pbDUiLCJpZCI6ImUyNWJlMzIwLTJlNWQtNDg2Ny05YTY1LWQ4YzQ5YmJlMTdlMiIsInJvbGVzIjpbIlJPTEVfVVNFUiJdLCJleHAiOjE3NTExMTUyOTJ9.byUsnlVq8XmkZ6dgzw0zPoLjdnJIgefEDyHYuhbCKM9xAAWlAHqGMQhrtarAPh8aoX1kgLRNYWWeR3Px4ZlBmQ
@adminToken = eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbjEiLCJpZCI6IjViYzM4OGE2LWY5NWQtNDU5ZC1iNWI1LTUxYjYzZTAxYzUzMyIsInJvbGVzIjpbIlJPTEVfVVNFUiIsIlJPTEVfQURNSU4iXSwiZXhwIjoxNzUxMTE1MzM1fQ.7m7TsuhxPwbSqfaaFmOrtZdvAnfVUjeVmYhK2f_PBUhO4gyUFi_0oLJbJ8wMYjFKZc-me1fE1qsNUeCiNj1LCA

### GET all accounts
GET {{path}}
Authorization: Bearer {{adminToken}}

### GET by id
GET {{path}}/{{accountId}}
Authorization: Bearer {{danilToken}}

### POST create new account
POST {{path}}
Content-Type: application/json
Authorization: Bearer {{danilToken}}

{
  "name": "!!! Test Danil !!!",
  "surname": "!!! Test Danil !!!",
  "age": 27
}

### PUT update account
PUT {{path}}/{{accountId}}
Content-Type: application/json
Authorization: Bearer {{danilToken}}

{
  "accountId": "{{accountId}}",
  "name": "Pashetet UPDATED BY ADMIN",
  "surname": "Petroshevich UPDATED BY ADMIN",
  "age": 24
}

### DELETE by id
DELETE {{path}}/{{accountId}}
Authorization: Bearer {{danilToken}}