spring:
  cloud:
    vault:
      uri: http://localhost:8200
      token: myroot
      kv:
        enabled: true
        backend: secret
        default-context: "kv/account-ms"

  datasource:
    url: jdbc:postgresql://localhost:5433/account_db?currentSchema=account_dev
    username: ${DB_USERNAME} # подтягиваются из vault
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      schema-locations: classpath:/sql/schema-dev.sql
      mode: always

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: account_dev

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yml

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      default-zone: http://localhost:8761/eureka/

server:
  port: 8100

logging:
  level:
    org.springframework.cloud.vault: DEBUG

springdoc:
  swagger-ui:
    config-url: /account/v3/api-docs/swagger-config
    url: /account/v3/api-docs
  api-docs:
    path: /account/v3/api-docs