spring:
  cloud:
    vault:
      uri: http://vault:8200

  datasource:
    url: jdbc:postgresql://postgres:5433/account_db?currentSchema=account_dev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: kafka:9092
