spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/account_db?currentSchema=account_dev

  jpa:
    show-sql: false

  kafka:
    bootstrap-servers: kafka:9092

logging:
  level:
    org.springframework.cloud.vault: INFO