spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/account_db?currentSchema=account_dev
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      schema-locations: classpath:/sql/schema-dev.sql
      mode: always

  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: account_dev

  liquibase:
    enabled: true
    change-log: db/changelog/db.changelog-master.yml

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      default-zone: http://localhost:8761/eureka/

server:
  port: 8100