@path = http://localhost:8110/api/v1/task
@taskId =281a9288-7474-4a8c-938c-7d18de0cebad

@profileId =5fd8f1f5-232e-4b39-adde-a256245e6a96


### GET all tasks by profile id
GET {{path}}?profileId={{profileId}}
Authorization: Bearer {{accessToken}}

### GET by id
GET {{path}}/{{taskId}}
Authorization: Bearer {{accessToken}}

### POST create new task
POST {{path}}
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "profileId":  "{{profileId}}",
  "title": "Fix some bugs",
  "body": "Couple of bugs haven't been solved yet. Have to cope with them",
  "completed": false
}

### PUT update task
PUT {{path}}/{{taskId}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "taskId": "{{taskId}}",
  "profileId":  "{{profileId}}",
  "title": "Test UPDATED",
  "body": "Test UPDATED",
  "completed": true
}

### DELETE by id
DELETE {{path}}/{{taskId}}
Authorization: Bearer {{accessToken}}
