@path = http://localhost:8110/api/v1/task
@taskId = 1664ca32-5d7d-43b9-adf8-455ba9de1318
@profileId = 4e4d7031-9ede-4968-b1dd-90b8d95d2a38


### GET by invalid UUID
GET {{path}}/it's-invalid-UUID

### GET unexisted task
GET {{path}}/{{taskId}}

### POST validation check
POST {{path}}
Content-Type: application/json

{
  "profileId":  "{{profileId}}",
  "title": "",
  "completed": false
}

### POST attempt creating with specified UUID
POST {{path}}
Content-Type: application/json

{
  "taskId": "{{taskId}}",
  "profileId":  "{{profileId}}",
  "title": "Test",
  "body": "Test",
  "completed": false
}

### PUT validation check
PUT {{path}}/{{taskId}}
Content-Type: application/json

{
  "profileId": "{{profileId}}",
  "title": "d",
  "body": ""
}

### PUT path profileId mismatch with entity taskId
PUT {{path}}/{{taskId}}
Content-Type: application/json

{
  "taskId": "1664ca32-5d7d-43b9-adf8-455ba9de1319",
  "profileId":  "{{profileId}}",
  "title": "Test",
  "body": "Test",
  "completed": false
}