@path = http://localhost:8120/api/v1/auth
@userId =edf491fe-e829-4212-9403-e34c8bee3bb4

### POST register
POST  {{path}}/register
Content-Type: application/json

{
    "username": "Danil14",
    "password": "root",
    "passwordConfirmation": "root"
}

### POST login
POST  {{path}}/login
Content-Type: application/json

{
    "username": "Danil14",
    "password": "root"
}

> {%
    client.global.set("accessToken", response.body.accessToken)
    client.global.set("refreshToken", response.body.refreshToken)
%}

### POST refresh
POST {{path}}/refresh

{{refreshToken}}

