@path = http://localhost:8120/api/v1/auth
@userId =edf491fe-e829-4212-9403-e34c8bee3bb4

### POST register
POST  {{path}}/register
Content-Type: application/json

{
    "username": "Ilysha",
    "password": "root",
    "passwordConfirmation": "root"
}

### POST login
POST  {{path}}/login
Content-Type: application/json

{
    "username": "Ilysha",
    "password": "root"
}

###
@refreshToken =eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJJbHlzaGEiLCJpZCI6IjUxNmVlNjYzLWE2NDQtNDllOC05YTU1LTNkMTJmZWJlMmJiMyIsImV4cCI6MTc1MTkxMTk3N30.n3tNDBXtiFsGLj9ecoe26QvLvLzrrOTjo5aa2QoKy_geRyvVRE5GhAIfppbXCqSb9RUgdKRXg4YzxnfSmy0NYg

### POST refresh
POST {{path}}/refresh

{{refreshToken}}

