@path=http://localhost:8120/api/v1/user

# ID пользователя, которого хотим сделать ADMIN'ом
@userId=9730e78d-056f-4873-a1d8-e6a19de19233

# Токен должен принадлежать пользователю с ролью ADMIN.
# Получить логин можно войдя в систему в auth-test.http

### PUT make user ADMIN
PUT {{path}}/{{userId}}
Authorization: Bearer {{accessToken}}

