name: Spring microservices monorepo CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.services }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            services/**

      - uses: ./.github/actions/list-changed
        with:
          files: ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Determine changed services
        id: filter
        run: |
          CHANGED_FILES="${{ steps.changed-files.outputs.all_changed_files }}"

          SERVICES=$(echo "$CHANGED_FILES" | grep -o 'services/[^/]*' | cut -d'/' -f2 | sort | uniq)

          echo "services=$(jq -nc '$SERVICES | split(" ")' --arg SERVICES "$SERVICES")" >> $GITHUB_OUTPUT
          
  build-and-test:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJSON(needs.detect-changes.outputs.services) }}
    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            services/${{ matrix.service }}/build  # Добавлен путь к build
          key: ${{ runner.os }}-gradle-${{ hashFiles('services/${{ matrix.service }}/**/*.gradle*', 'services/${{ matrix.service }}/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        working-directory: ./services/${{ matrix.service }}
        shell: bash
        run: chmod +x gradlew

      - name: Run tests and build
        working-directory: ./services/${{ matrix.service }}
        shell: bash
        run: ./gradlew build