name: Spring microservices monorepo CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      services: ${{ steps.filter.outputs.services }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v46
        with:
          files: |
            services/**

      - uses: ./.github/actions/list-changed
        with:
          files: ${{ steps.changed-files.outputs.all_changed_files }}

      - name: Determine changed services
        id: filter
        run: |
          CHANGED_FILES="${{ steps.changed-files.outputs.all_changed_files }}"
          
          SERVICES=$(echo "$CHANGED_FILES" | grep -o 'services/[^/]*' | cut -d'/' -f2 | sort | uniq | jq -R -s -c 'split("\n") | map(select(. != ""))')
          
          echo "services=${SERVICES}" >> $GITHUB_OUTPUT
          echo "Detected changed services: ${SERVICES}"
          
  build-and-test:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ${{ fromJSON(needs.detect-changes.outputs.services) }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Verify service directory
        run: |
          if [ ! -d "services/${{ matrix.service }}" ]; then
            echo "::error::Directory services/${{ matrix.service }} does not exist!"
            exit 1
          fi

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            services/${{ matrix.service }}/build
          key: ${{ runner.os }}-gradle-${{ matrix.service }}-${{ hashFiles('services/${{ matrix.service }}/build.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-${{ matrix.service }}-
            ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        working-directory: ./services/${{ matrix.service }}
        run: |
          if [ -f "gradlew" ]; then
            chmod +x gradlew
          else
            echo "::warning::gradlew not found in ${{ matrix.service }}"
            exit 1
          fi

      - name: Run tests and build
        working-directory: ./services/${{ matrix.service }}
        run: ./gradlew build